// <auto-generated />
using System;
using Measurement_MC_App.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Measurement_MC_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209092948_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Measurement_MC_App.Models.Database.Connector", b =>
                {
                    b.Property<int>("ConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AxisXMax")
                        .HasColumnType("int");

                    b.Property<int>("AxisYMax")
                        .HasColumnType("int");

                    b.Property<int>("AxisZMax")
                        .HasColumnType("int");

                    b.Property<int>("BaudRate")
                        .HasColumnType("int");

                    b.Property<int>("DataBits")
                        .HasColumnType("int");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("SafeZ")
                        .HasColumnType("int");

                    b.Property<int>("SpeedX")
                        .HasColumnType("int");

                    b.Property<int>("SpeedY")
                        .HasColumnType("int");

                    b.Property<int>("SpeedZ")
                        .HasColumnType("int");

                    b.Property<string>("StopBits")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("ConnectorId");

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("Measurement_MC_App.Models.Database.Logs", b =>
                {
                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("column")
                        .HasColumnType("int");

                    b.Property<double>("height")
                        .HasColumnType("double");

                    b.Property<int>("row")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("trayId")
                        .HasColumnType("int");

                    b.Property<double>("width")
                        .HasColumnType("double");

                    b.HasKey("ModelId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Measurement_MC_App.Models.Database.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("NominalX")
                        .HasColumnType("double");

                    b.Property<double>("NominalY")
                        .HasColumnType("double");

                    b.Property<double>("TolXMinus")
                        .HasColumnType("double");

                    b.Property<double>("TolXPlus")
                        .HasColumnType("double");

                    b.HasKey("ModelId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Measurement_MC_App.Models.Database.PointParam", b =>
                {
                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("point1X")
                        .HasColumnType("int");

                    b.Property<int>("point1Y")
                        .HasColumnType("int");

                    b.Property<int>("point1Z")
                        .HasColumnType("int");

                    b.Property<int>("point2X")
                        .HasColumnType("int");

                    b.Property<int>("point2Y")
                        .HasColumnType("int");

                    b.Property<int>("point2Z")
                        .HasColumnType("int");

                    b.Property<int>("point3X")
                        .HasColumnType("int");

                    b.Property<int>("point3Y")
                        .HasColumnType("int");

                    b.Property<int>("point3Z")
                        .HasColumnType("int");

                    b.Property<int>("point4X")
                        .HasColumnType("int");

                    b.Property<int>("point4Y")
                        .HasColumnType("int");

                    b.Property<int>("point4Z")
                        .HasColumnType("int");

                    b.Property<int>("point5X")
                        .HasColumnType("int");

                    b.Property<int>("point5Y")
                        .HasColumnType("int");

                    b.Property<int>("point5Z")
                        .HasColumnType("int");

                    b.Property<int>("point6X")
                        .HasColumnType("int");

                    b.Property<int>("point6Y")
                        .HasColumnType("int");

                    b.Property<int>("point6Z")
                        .HasColumnType("int");

                    b.HasKey("ModelId");

                    b.ToTable("PointParams");
                });

            modelBuilder.Entity("Measurement_MC_App.Models.Database.VisionParam", b =>
                {
                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<double>("Blur")
                        .HasColumnType("double");

                    b.Property<double>("CannyHigh")
                        .HasColumnType("double");

                    b.Property<double>("CannyLow")
                        .HasColumnType("double");

                    b.Property<double>("MmPerPixelHeight")
                        .HasColumnType("double");

                    b.Property<double>("MmPerPixelWidth")
                        .HasColumnType("double");

                    b.Property<double>("RealObjectHeight")
                        .HasColumnType("double");

                    b.Property<double>("RealObjectWidth")
                        .HasColumnType("double");

                    b.Property<double>("RefObjectHeight")
                        .HasColumnType("double");

                    b.Property<double>("RefObjectWidth")
                        .HasColumnType("double");

                    b.HasKey("ModelId");

                    b.ToTable("VisionParams");
                });

            modelBuilder.Entity("Measurement_MC_App.Models.Database.Logs", b =>
                {
                    b.HasOne("Measurement_MC_App.Models.Database.Model", "Model")
                        .WithOne("Logs")
                        .HasForeignKey("Measurement_MC_App.Models.Database.Logs", "ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Measurement_MC_App.Models.Database.PointParam", b =>
                {
                    b.HasOne("Measurement_MC_App.Models.Database.Model", "Model")
                        .WithOne("PointParam")
                        .HasForeignKey("Measurement_MC_App.Models.Database.PointParam", "ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Measurement_MC_App.Models.Database.VisionParam", b =>
                {
                    b.HasOne("Measurement_MC_App.Models.Database.Model", "Model")
                        .WithOne("VisionParam")
                        .HasForeignKey("Measurement_MC_App.Models.Database.VisionParam", "ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Measurement_MC_App.Models.Database.Model", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("PointParam");

                    b.Navigation("VisionParam");
                });
#pragma warning restore 612, 618
        }
    }
}
